### ISSUE TITLE
spans don't appear in jaeger until the span closes

### ISSUE THREAD

**Issue by little-dude** [jtescher/tracing-opentelemetry#11]
Hello :wave: 

First thanks a lot for this crate. I'm a newbie in the world of tracing and `tracing-opentelemetry` was really easy to use.

------

I'd like to monitor a running application with `jaeger`, but I have a bunch of long lived spans, and they don't appear in `jaeger` until the program terminates (if it terminates properly).

This is reproducible using the example in this repo, by just adding an infinite loop:

```
fn main() -> thrift::Result<()> {
    init_tracer()?;
    let tracer = global::trace_provider().get_tracer("tracing");
    let opentelemetry = OpentelemetryLayer::with_tracer(tracer);
    let subscriber = opentelemetry.with_subscriber(Registry::default());

    tracing::subscriber::with_default(subscriber, || {
        let root = span!(tracing::Level::INFO, "app_start", work_units = 2);
        let _enter = root.enter();

        loop {
            span!(tracing::Level::INFO, "faster_work")
                .in_scope(|| thread::sleep(Duration::from_millis(100)));
        }

        warn!("About to exit!");
    });

    // Allow flush
    thread::sleep(Duration::from_millis(250));

    Ok(())
}
```

The `app_start` span will never be shown, even after interrupting the program with `^C`.

**Comment by jtescher** [comment]
Hey @little-dude, the issue in this example seems to be that the allow flush sleep line never gets reached when you `^C` so the root spans do not have time to get recorded. Spans in general are reported when they end (usually when dropped in rust), so if you have long lived spans they will not appear until they are dropped.

**Comment by little-dude** [comment]
Thanks for the answer @jtescher 

> Spans in general are reported when they end (usually when dropped in rust), so if you have long lived spans they will not appear until they are dropped.

Is that something inherent to tracing itself or just to `tracing-opentelemetry`?

**Comment by jtescher** [comment]
Tracing is less opinionated about how spans work and leaves things up to the subscriber/layers so it can be flexible enough to support many use cases. 

`tracing-opentelemetry` doesn't require this either technically, however this is how most tracing libraries expect spans to be reported _by_ Open Telemetry, typically systems like Jaeger require the span duration at the time they are reported so they can display things like timelines. You can see how [opentelemetry-jaeger](https://github.com/open-telemetry/opentelemetry-rust/tree/master/opentelemetry-jaeger) and [opentelemetry-zipkin](https://github.com/open-telemetry/opentelemetry-rust/tree/master/opentelemetry-zipkin) work currently to report spans.

**Comment by little-dude** [comment]
Ah thank you for the explanation! I'll take a look at the code for the details.

Edit: I'll close this then :) Thanks again!
