### ISSUE TITLE
Root spans not sent when using Sampler::Probability

### ISSUE THREAD

**Issue by samschlegel** [jtescher/tracing-opentelemetry#19]
Working on getting a minimal repro, but it appears that when using the sampler set to Probability, the root span is never reported. Child spans are reported just fine, and setting the sampler to Always seems to fix this so I don't think it's related to flushing, especially since I'm seeing this when using `with_simple_exporter`

I'm not sure if this is an upstream issue, so I'm going to test there first.

**Comment by samschlegel** [comment]
Ah, from a quick glance this might be fixed in https://github.com/open-telemetry/opentelemetry-rust/pull/93

**Comment by samschlegel** [comment]
Yep! Fixed there.

**Comment by jtescher** [comment]
Resolved in https://github.com/tokio-rs/tracing/pull/713
